<?php

namespace Database\Seeders\Support;

/**
 * Arabic labels for seeder strings (paired with English keys used in seeders).
 */
final class SeedArabic
{
    /**
     * @return array<string, string>
     */
    public static function animals(): array
    {
        return [
            'Holstein Cow' => 'بقرة هولشتاين',
            'Baladi Cow' => 'بقرة بلدي',
            'Friesian Cattle' => 'ماشية فريزيان',
            'Buffalo' => 'جاموس',
            'Ossimi Sheep' => 'غنم أوسيمي',
            'Rahmani Sheep' => 'غنم رحماني',
            'Barki Sheep' => 'غنم برقي',
            'Awassi Sheep' => 'غنم عواسي',
            'Zaraibi Goat' => 'ماعز زرابي',
            'Shami Goat' => 'ماعز شامي',
            'Baladi Goat' => 'ماعز بلدي',
            'Nubian Goat' => 'ماعز نوبي',
            'Broiler Chicken' => 'دجاج لاحم',
            'Layer Chicken' => 'دجاج بياض',
            'Baladi Chicken' => 'دجاج بلدي',
            'Duck' => 'بط',
            'Turkey' => 'ديك رومي',
            'Arabian Horse' => 'حصان عربي',
            'Thoroughbred' => 'حصان إنجليزي أصيل',
            'Donkey' => 'حمار',
            'Dromedary Camel' => 'جمل مجهود',
            'Racing Camel' => 'جمل سباق',
            'New Zealand White' => 'أرنب نيوزيلندي أبيض',
            'Baladi Rabbit' => 'أرنب بلدي',
            'Rex Rabbit' => 'أرنب ركس',
            'Nile Tilapia' => 'بلطي النيل',
            'Catfish' => 'سمك القرموط',
            'Mullet' => 'بوري',
        ];
    }

    public static function animalName(string $en): string
    {
        return self::animals()[$en] ?? $en;
    }

    /**
     * @return array<string, string>
     */
    public static function vaccines(): array
    {
        return [
            'FMD (Foot & Mouth)' => 'حمى قلاعية (فم وأقدام)',
            'Brucellosis' => 'الحمى المالطية (داء البروسيلات)',
            'Anthrax' => 'جمرة خبيثة',
            'LSD (Lumpy Skin Disease)' => 'داء الجلد العقدي',
            'Blackleg' => 'الوذمة الرئوية / الساق السوداء',
            'Sheep Pox' => 'جدري الأغنام',
            'Enterotoxemia' => 'التسمم المعوي (انتيروتوكسيميا)',
            'Goat Pox' => 'جدري الماعز',
            'Newcastle Disease (NDV)' => 'نيوكاسل (داء نيوكاسل)',
            'Avian Influenza (H5N1)' => 'إنفلونزا الطيور (H5N1)',
            'Gumboro (IBD)' => 'جامبورو (التهاب حويصلة فبرية)',
            "Marek's Disease" => 'داء ماريك',
            'Infectious Bronchitis' => 'التهاب قصبات معدي',
        ];
    }

    public static function vaccineName(string $en): string
    {
        $map = self::vaccines();

        return $map[$en] ?? $en;
    }

    /**
     * @return array<string, string>
     */
    public static function locations(): array
    {
        return array_merge(self::cities(), self::regions());
    }

    /**
     * @return array<string, string>
     */
    private static function cities(): array
    {
        return [
            'Nasr City' => 'مدينة نصر',
            'Heliopolis' => 'مصر الجديدة',
            'Maadi' => 'المعادي',
            'Zamalek' => 'الزمالك',
            'Shubra' => 'شبرا',
            'New Cairo' => 'القاهرة الجديدة',
            'Giza City' => 'مدينة الجيزة',
            '6th of October' => 'السادس من أكتوبر',
            'Sheikh Zayed' => 'الشيخ زايد',
            'Haram' => 'الهرم',
            'Dokki' => 'الدقي',
            'Alexandria City' => 'مدينة الإسكندرية',
            'Borg El Arab' => 'برج العرب',
            'Amreya' => 'العامرية',
            'Mansoura' => 'المنصورة',
            'Mit Ghamr' => 'ميت غمر',
            'Talkha' => 'طلخا',
            'Aga' => 'أجا',
            'Belqas' => 'بلقاس',
            'Dikirnis' => 'دكرنس',
            'Sinbillawin' => 'السنبلاوين',
            'Sherbin' => 'شربين',
            'Hurghada' => 'الغردقة',
            'Safaga' => 'سفاجا',
            'El Qoseir' => 'القصير',
            'Damanhour' => 'دمنهور',
            'Kafr El Dawwar' => 'كفر الدوار',
            'Rashid' => 'رشيد',
            'Idku' => 'إدكو',
            'Fayoum City' => 'مدينة الفيوم',
            'Ibshaway' => 'إبشواي',
            'Tamiya' => 'طامية',
            'Sinnuris' => 'سنورس',
            'Tanta' => 'طنطا',
            'El Mahalla El Kubra' => 'المحلة الكبرى',
            'Zefta' => 'زفتى',
            'Samannoud' => 'سمنود',
            'Ismailia City' => 'مدينة الإسماعيلية',
            'Fayed' => 'فايد',
            'Qantara West' => 'القنطرة غرب',
            'Shibin El Kom' => 'شبين الكوم',
            'Menouf' => 'منوف',
            'Ashmoun' => 'أشمون',
            'Sadat City' => 'مدينة السادات',
            'Minya City' => 'مدينة المنيا',
            'Mallawi' => 'ملوي',
            'Beni Mazar' => 'بني مزار',
            'Maghagha' => 'مغاغة',
            'Banha' => 'بنها',
            'Qalyub' => 'قليوب',
            'Khanka' => 'الخانكة',
            'Shubra El Kheima' => 'شبرا الخيمة',
            'Kharga' => 'الخارجة',
            'Mut' => 'موط',
            'Dakhla' => 'الداخلة',
            'Suez City' => 'مدينة السويس',
            'Arbaeen' => 'الأربعين',
            'Faisal' => 'فيصل',
            'Ganayen' => 'الجناين',
            'Asyut City' => 'مدينة أسيوط',
            'Dayrout' => 'ديروط',
            'Abnoub' => 'أبنوب',
            'Manfalut' => 'منفلوط',
            'Sharm El Sheikh' => 'شرم الشيخ',
            'Dahab' => 'دهب',
            'Nuweiba' => 'نويبع',
            'Saint Catherine' => 'سانت كاترين',
            'Kafr El Sheikh City' => 'مدينة كفر الشيخ',
            'Desouk' => 'دسوق',
            'Baltim' => 'بلطيم',
            'Sidi Salem' => 'سيدي سالم',
            'Marsa Matruh' => 'مرسى مطروح',
            'El Alamein' => 'العلمين',
            'Siwa' => 'سيوة',
            'El Negaila' => 'النجيلة',
            'Luxor City' => 'مدينة الأقصر',
            'Esna' => 'إسنا',
            'Armant' => 'أرمنت',
            'El Tod' => 'الطود',
            'Qena City' => 'مدينة قنا',
            'Nag Hammadi' => 'نجع حمادي',
            'Dishna' => 'دشنا',
            'Farshut' => 'فرشوط',
            'Arish' => 'العريش',
            'Sheikh Zuweid' => 'الشيخ زويد',
            'Rafah' => 'رفح',
            'Bir El Abd' => 'بئر العبد',
            'Sohag City' => 'مدينة سوهاج',
            'Akhmim' => 'أخميم',
            'Girga' => 'جرجا',
            'Tahta' => 'طهطا',
            'Beni Suef City' => 'مدينة بني سويف',
            'Nasser' => 'ناصر',
            'Ihnasiya' => 'إهناسيا',
            'El Wasta' => 'الواسطى',
            'Port Said City' => 'مدينة بورسعيد',
            'Port Fouad' => 'بورفؤاد',
            'Arab Quarter' => 'الحي العربي',
            'Damietta City' => 'مدينة دمياط',
            'Ras El Bar' => 'رأس البر',
            'Faraskour' => 'فارسكور',
            'Kafr Saad' => 'كفر سعد',
            'Aswan City' => 'مدينة أسوان',
            'Kom Ombo' => 'كوم أمبو',
            'Edfu' => 'إدفو',
            'Daraw' => 'دراو',
            'Zagazig' => 'الزقازيق',
            'Belbeis' => 'بلبيس',
            'Minya El Qamh' => 'منيا القمح',
            'Abu Hammad' => 'أبو حماد',
        ];
    }

    /**
     * @return array<string, string>
     */
    private static function regions(): array
    {
        return [
            'Nasr City 1' => 'مدينة نصر 1',
            'Nasr City 2' => 'مدينة نصر 2',
            'Al Hay Al Ashir' => 'الحي العاشر',
            'Roxy' => 'روكسي',
            'Korba' => 'الكوربة',
            'Mirghani' => 'مرغني',
            'Degla' => 'دجلة',
            'Sarayat' => 'السرايات',
            'Corniche Maadi' => 'كورنيش المعادي',
            'Gezira Center' => 'وسط الجزيرة',
            '26 July Street' => 'شارع 26 يوليو',
            'Mariette' => 'مارييت',
            'Shubra North' => 'شبرا شمال',
            'Shubra South' => 'شبرا جنوب',
            'Rod El Farag' => 'روض الفرج',
            'First District' => 'الحي الأول',
            'Fifth Settlement' => 'التجمع الخامس',
            'Narges' => 'النرجس',
            'Dokki Side' => 'جانب الدقي',
            'Faisal Street' => 'شارع فيصل',
            'Haram Street' => 'شارع الهرم',
            'Industrial Zone' => 'منطقة صناعية',
            'Residential A' => 'سكني أ',
            'Hosary' => 'الحصري',
            'Zayed 1' => 'زايد 1',
            'Zayed 2' => 'زايد 2',
            'Green Belt' => 'الحزام الأخضر',
            'Pyramids Road' => 'طريق الأهرام',
            'Nazlet El Samman' => 'نزلة السمان',
            'Remaya' => 'الرمية',
            'Orman' => 'الأورمان',
            'Mesaha' => 'المساحة',
            'Tahrir Extension' => 'امتداد التحرير',
            'Mansheya' => 'المنشية',
            'Raml Station' => 'محطة الرمل',
            'Sidi Gaber' => 'سيدي جابر',
            'New Borg' => 'برج العرب الجديدة',
            'Industrial' => 'منطقة صناعية',
            'Residential West' => 'سكني غرب',
            'Amreya Center' => 'وسط العامرية',
            'King Mariout' => 'مريوط',
            'North Coast Strip' => 'شريط الساحل الشمالي',
            'Al Mansurah Center' => 'وسط المنصورة',
            'Gesr El Suez' => 'جسر السويس',
            'Bahr El Saghir' => 'بحر الصغير',
            'Mit Ghamr Center' => 'وسط ميت غمر',
            'Al Barha' => 'البرها',
            'Samalut Road' => 'طريق سمالوط',
            'Talkha Center' => 'وسط طلخا',
            'Nabarouh Road' => 'طريق نبروه',
            'Belqas Link' => 'ربط بلقاس',
            'Aga Center' => 'وسط أجا',
            'East Villages' => 'قرى شرقية',
            'West Villages' => 'قرى غربية',
            'Belqas Center' => 'وسط بلقاس',
            'Farmland North' => 'أراضي زراعية شمال',
            'Farmland South' => 'أراضي زراعية جنوب',
            'Dikirnis Center' => 'وسط دكرنس',
            'Highway Side' => 'جانب الطريق السريع',
            'Rail Side' => 'جانب السكة',
            'Sinbillawin Center' => 'وسط السنبلاوين',
            'Villages Cluster' => 'تجمع قرى',
            'Market Area' => 'منطقة السوق',
            'Sherbin Center' => 'وسط شربين',
            'East Delta' => 'شرق الدلتا',
            'Canal Side' => 'جانب الترعة',
            'Dahar' => 'الدهار',
            'Sakala' => 'السقالة',
            'El Gouna Road' => 'طريق الجونة',
            'Port Area' => 'منطقة الميناء',
            'Residential' => 'سكني',
            'Old Town' => 'البلدة القديمة',
            'New Corniche' => 'كورنيش جديد',
            'South Villages' => 'قرى جنوبية',
            'City Center' => 'وسط البلد',
            'Railway' => 'محطة السكة',
            'University Area' => 'منطقة الجامعة',
            'Textile Zone' => 'منطقة الغزل',
            'Canal' => 'جانب الترعة',
            'Historic Core' => 'القلب التاريخي',
            'Port Quarter' => 'حي الميناء',
            'Delta Edge' => 'حافة الدلتا',
            'Lake Side' => 'جانب البحيرة',
            'Main Street' => 'الشارع الرئيسي',
            'Farms' => 'مزارع',
            'Sinai' => 'سيناء',
            'Lake Quarter' => 'حي البحيرة',
            'University' => 'الجامعة',
            'Ibshaway Center' => 'وسط إبشواي',
            'Canal Villages' => 'قرى الترعة',
            'Desert Edge' => 'حافة الصحراء',
            'Tamiya Center' => 'وسط طامية',
            'Oasis Road' => 'طريق الواحات',
            'Agricultural' => 'زراعي',
            'Sinnuris Center' => 'وسط سنورس',
            'North Fields' => 'حقول شمالية',
            'South Fields' => 'حقول جنوبية',
            'Market' => 'السوق',
            'Spinning District' => 'حي الغزل',
            'Zefta Center' => 'وسط زفتى',
            'Canal East' => 'شرق الترعة',
            'Canal West' => 'غرب الترعة',
            'Samannoud Center' => 'وسط سمنود',
            'Villages' => 'قرى',
            'Highway' => 'طريق سريع',
            'Ferry Area' => 'منطقة العبّارة',
            'Third District' => 'الحي الثالث',
            'Lake View' => 'إطلالة على البحيرة',
            'Fayed Center' => 'وسط فايد',
            'Border Zone' => 'منطقة حدودية',
            'Hospital Area' => 'منطقة المستشفى',
            'Old Market' => 'السوق القديم',
            'Menouf Center' => 'وسط منوف',
            'Rail Villages' => 'قرى السكة',
            'Ashmoun Center' => 'وسط أشمون',
            'Ashmoun Bridge' => 'كوبري أشمون',
            'Fields' => 'حقول',
            'Industrial City' => 'مدينة صناعية',
            'Logistics' => 'لوجستيات',
            'Palace Area' => 'منطقة القصر',
            'Corniche' => 'الكورنيش',
            'New Minya' => 'المنيا الجديدة',
            'Mallawi Center' => 'وسط ملوي',
            'Upper Egypt Road' => 'طريق صعيد مصر',
            'Beni Mazar Center' => 'وسط بني مزار',
            'Desert' => 'صحراء',
            'Maghagha Center' => 'وسط مغاغة',
            'Nile Side' => 'جانب النيل',
            'Ring Road' => 'الطريق الدائري',
            'Qalyub Center' => 'وسط قليوب',
            'Khanka Center' => 'وسط الخانكة',
            'Desert Extension' => 'امتداد صحراوي',
            'Shubra Kheima 1' => 'شبرا الخيمة 1',
            'Shubra Kheima 2' => 'شبرا الخيمة 2',
            'Factories' => 'مصانع',
            'Kharga Center' => 'وسط الخارجة',
            'Oasis Ring' => 'حلقة الواحة',
            'Desert Road' => 'طريق صحراوي',
            'Mut Center' => 'وسط موط',
            'Dakhla Link' => 'ربط الداخلة',
            'Dakhla Town' => 'بلدة الداخلة',
            'Hot Springs' => 'ينابيع ساخنة',
            'Arbaeen' => 'الأربعين',
            'Faisal' => 'فيصل',
            'Port Tawfiq' => 'بورتوفيق',
            'Arbaeen Center' => 'وسط الأربعين',
            'Petrochemical' => 'بتروكيماويات',
            'Workers Housing' => 'سكن عمال',
            'Faisal Center' => 'وسط فيصل',
            'Canal View' => 'إطلالة على القناة',
            'Ganayen Center' => 'وسط الجناين',
            'Dayrout Center' => 'وسط ديروط',
            'Abnoub Center' => 'وسط أبنوب',
            'Manfalut Center' => 'وسط منفلوط',
            'Naama Bay' => 'خليج نعمة',
            'Hadaba' => 'الهضبة',
            'Nabq' => 'نبق',
            'Masbat' => 'المصباط',
            'Assalah' => 'السلاح',
            'Blue Hole Road' => 'طريق الحفرة الزرقاء',
            'Port' => 'الميناء',
            'Colored Canyon Road' => 'طريق الملون',
            'Beach' => 'الشاطئ',
            'Monastery Area' => 'منطقة الدير',
            'Mountain Trail' => 'مسار جبلي',
            'Bedouin' => 'منطقة بدوية',
            'Center' => 'المركز',
            'Desouk Center' => 'وسط دسوق',
            'Baltim Beach' => 'شاطئ بلطيم',
            'Lagoon' => 'البحيرة',
            'Sidi Salem Center' => 'وسط سيدي سالم',
            'Rice Fields' => 'حقول أرز',
            'Road' => 'طريق',
            'Cleopatra' => 'كليوباترا',
            'Agiba' => 'العجيبة',
            'North Coast' => 'الساحل الشمالي',
            'Memorial' => 'المعلم التذكاري',
            'New Marina' => 'مارينا جديدة',
            'Shali' => 'شالي',
            'Fatnas' => 'فتناس',
            'Desert Springs' => 'ينابيع صحراوية',
            'Negaila Center' => 'وسط النجيلة',
            'Coast' => 'ساحل',
            'East Bank' => 'الضفة الشرقية',
            'West Bank Ferry' => 'عبّارة الضفة الغربية',
            'Karnak' => 'الكرنك',
            'Esna Lock' => 'قفل إسنا',
            'Town Center' => 'وسط البلدة',
            'Sugar Factory' => 'مصنع سكر',
            'El Tod Center' => 'وسط الطود',
            'Nag Hammadi Center' => 'وسط نجع حمادي',
            'Sugar' => 'سكر',
            'Bridge' => 'كوبري',
            'Dishna Center' => 'وسط دشنا',
            'Upper Villages' => 'قرى عليا',
            'Farshut Center' => 'وسط فرشوط',
            'Coastal' => 'ساحلي',
            'Border Villages' => 'قرى حدودية',
            'Rafah Crossing Area' => 'منطقة معبر رفح',
            'East' => 'شرق',
            'Akhmim Center' => 'وسط أخميم',
            'Antiquities' => 'الآثار',
            'Nile' => 'النيل',
            'Girga Center' => 'وسط جرجا',
            'Tahta Center' => 'وسط طهطا',
            'Nasser Center' => 'وسط ناصر',
            'Ihnasiya Center' => 'وسط إهناسيا',
            'Historic' => 'تاريخي',
            'El Wasta Center' => 'وسط الواسطى',
            'Arab District' => 'الحي العربي',
            'Port Area' => 'منطقة الميناء',
            'Gardens' => 'الحدائق',
            'Port Fouad Center' => 'وسط بورفؤاد',
            'Fishing Port' => 'ميناء صيد',
            'Schools' => 'مدارس',
            'New Damietta' => 'دمياط الجديدة',
            'Furniture' => 'الأثاث',
            'Beach' => 'الشاطئ',
            'Faraskour Center' => 'وسط فارسكور',
            'Kafr Saad Center' => 'وسط كفر سعد',
            'Industry' => 'صناعة',
            'Elephantine' => 'الجزيرة',
            'High Dam' => 'السد العالي',
            'Temple Area' => 'منطقة المعبد',
            'Edfu Temple' => 'معبد إدفو',
            'Camel Market' => 'سوق الجمال',
            'Tenth' => 'العاشر من رمضان',
            'Belbeis Center' => 'وسط بلبيس',
            'Minya Qamh Center' => 'وسط منيا القمح',
            'Abu Hammad Center' => 'وسط أبو حماد',
        ];
    }

    public static function location(string $en): string
    {
        $dict = self::locations();

        return $dict[$en] ?? $en;
    }
}
